version: '3.8'

services:
  backend:
    build:
      context: ./backend
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "8080:8080"
    environment:
      - MONGODB_CONNECTION_STRING=mongodb+srv://anhduyking:doanhduy2003@cluster0cloudfrog.e7b3g.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0cloudfrog
      - SFTP_HOST=duynas.duckdns.org
      - SFTP_PORT=9333
      - SFTP_USER=admin
      - SFTP_PASSWORD=Doanhduy2003
      - SFTP_PATH=/DuyData/cloud
      - BASE_URL=http://localhost:8080

  frontend:
    build:
      context: ./frontend
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
